services:
  # consul app for service discovery
  consul.app:
    container_name: consul-aws-ecs
    image: hashicorp/consul:1.20
    ports:
      - "8500:8500"
    networks:
      - web

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8082:80"
    networks:
      - web

  hello-service:
    build: ./hello-service
    container_name: hello-service
    # ports:
    #   - "8081:80"
    networks:
      - web

networks:
  web:
    driver: bridge
