
services:
  postgres:
    image: postgres:16.3-alpine
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ~/go-projects/db/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  # jaeger set up
  jaeger:
    image: jaegertracing/jaeger:2.1.0
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"
      - "4318:4318"   # OTLP HTTP
      - "5778:5778"
      - "9411:9411"
volumes:
  postgres-data:
    driver: local