
services:
  # Service Discovery
  consul.alka:
    container_name: consul-service
    image: hashicorp/consul:1.20
    ports:
      - "8500:8500" # Consul UI
    networks:
      - web
    restart: always
    
#########################################
  # Gateway Service Containers
#########################################
  gateway-service.alka:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "80:80"
    depends_on:
      - consul.alka
    networks:
      - web


  user-postgres.alka:
    image: postgres:16.3-alpine
    container_name: user-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./project/user-postgres/postgres/:/var/lib/postgresql/data/
    networks:
      - web

  product-postgres.alka:
    image: postgres:16.3-alpine
    container_name: product-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./project/product-postgres/postgres/:/var/lib/postgresql/data/
    networks:
      - web

  order-postgres.alka:
    image: postgres:16.3-alpine
    container_name: order-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./project/order-postgres/postgres/:/var/lib/postgresql/data/
    networks:
      - web

  adminer.alka:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"
    networks:
      - web
  

#######################################
# User-Service containers
#######################################

  user-service.alka:
    build: ./user-service
    # remove this name to scale this service
    container_name: user-service
    # remove the ports as we don't want to expose the ports
    # ports:
      # - "8083:80"
    depends_on:
      - consul.alka
      - user-postgres.alka
    networks:
      - web


#######################################
# Product-Service containers
#######################################

  product-service.alka:
    build: ./product-service
    # remove this name to scale this service
    container_name: product-service
    # remove the ports as we don't want to expose the ports
    ports:
      # - "8083:80"
      # expose this to test on postman
      - "5001:5001"
    depends_on:
      - consul.alka
      - product-postgres.alka
    networks:
      - web

  order-service.alka:
    build: ./order-service
    # remove this name to scale this service
    container_name: order-service
    # remove the ports as we don't want to expose the ports
    # ports:
      # - "8083:80"
    depends_on:
      - consul.alka
      - order-postgres.alka
    networks:
      - web

  kafka-user-service.alka:
    image: apache/kafka:3.9.0
    container_name: kafka-user-service
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-user-service.alka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - web

  kafka-order-service.alka:
    image: apache/kafka:3.9.0
    container_name: kafka-order-service
    ports:
      - "9093:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-order-service.alka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - web

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    depends_on:
      - kafka-user-service.alka
      - kafka-order-service.alka
    environment:
      KAFKA_CLUSTERS_0_NAME: user-service-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-user-service.alka:9092
      KAFKA_CLUSTERS_1_NAME: order-service-cluster
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka-order-service.alka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - web
      

#Containers connected to the same bridge network can communicate with each other
networks:
  web:
    driver: bridge