up:
	docker compose up --build -d

down:
	docker compose down


generate-key-pair:
	openssl genpkey -algorithm RSA -out private.pem -pkeyopt rsa_keygen_bits:2048
	openssl rsa -in private.pem -pubout -out pubkey.pem


create multiple instances of user service:
	docker compose up --build -d --scale user-service.alka=3


# docker image cleanup
docker prune 
docker system prune -a
 


docker build --tag 'order-service' .
docker run --detach 'order-service'